services:
  backend:
    build: .
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/app
      - /app/node_modules
    command: ['node', 'dist/main']
    networks:
      - backend
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - backend
networks:
  backend:

volumes:
  redis_data:
